networks:
  toubeelib.net:
    driver: bridge
    
services:

  # service api.toubeelib : api pour la prise de rdv
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    container_name: toubeelib.api
    env_file: ./toubeelib.env.dist
    ports:
      - '6080:80'
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    networks:
      - toubeelib.net
    depends_on:
      - db

  # service toubeelib.db : base de données postgresql
  db:
    image: postgres:16.1
    container_name: toubeelib.db
    environment:
      POSTGRES_DB: toubeelib
      POSTGRES_USER: toubeelib
      POSTGRES_PASSWORD: toubeelib
    ports:
      - '5432:5432'
    networks:
      - toubeelib.net
    volumes:
      - ./sql/01-toubee_auth.schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./sql/02-toubeelib.schema.sql:/docker-entrypoint-initdb.d/02-schema.sql
      - ./sql/03-toubee_auth.data.sql:/docker-entrypoint-initdb.d/03-data.sql
      - ./sql/04-toubeelib.data.sql:/docker-entrypoint-initdb.d/04-data.sql
  
  # service administration des bases sql
  adminer:
    image: adminer
    container_name: toubeelib.adminer
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - '8080:8080'
    networks:
      - toubeelib.net
    depends_on:
      - db
